// List / Index Url
GET http://localhost:3535/users

###

// Create / Store Url
POST http://localhost:3535/users HTTP/1.1
Content-Type: application/json

{
  "name": "Leonardo Coutinho",
  "email": "leonardo@gmail.com"
}

###

// Read / Show Url
GET http://localhost:3535/users/3

###

// Update Url
PUT http://localhost:3535/users/3 HTTP/1.1
Content-Type: application/json

{
  "name": "Rafael P. Coutinho",
  "email": "rafael@gmail.com"
}

###

// Delete / Destroy Url
DELETE http://localhost:3535/users/12
